[package]
name = "zetaos"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics-core = "0.4.0"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
limine = "0.2.0"
tinybmp = "0.6.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
